#!/bin/sh
exec 1>&2

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff-index $against|(cd ../repo-overlay; patch -p1 --dry-run)
